### ISSUE TITLE
Rename Bus to Event

### ISSUE THREAD

**Issue by mattak** [mattak/Unibus#3]
It seems more readable.

``` cs
Bus.Instance.Dispatch("");
Bus.Instance.Subscribe(OnEvent);
Bus.Instance.Unsubscribe(OnEvent);
```

``` cs
Event.Instance.Dispatch("");
Event.Instance.Subscribe(OnEvent);
Event.Instance.Unsubscribe(OnEvent);
```

**Comment by kazuman519** [comment]
Bus is likely to be used as the name of the object.

**Comment by kazuman519** [comment]
I prefer `Unibus` than `Event`.

**Comment by mattak** [comment]
I think carefully about namespace and class name relationship, then find some libraries using different name.
1. Json.Net => namespace: Newtonsoft.Json / class: [JsonConvert](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonConvert.cs#L54)
2. AutoMapper => namespace: AutoMapper / class: [Mapper](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Mapper.cs#L10)
3. NUnit => namespace: NUnit.Framework / class: [Assert](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Assert.cs#L49)
4. NLog => namespace: NLog / class: [Logger](https://github.com/NLog/NLog/blob/master/src/NLog/Logger.cs#L48)
5. Moq => namespace: Moq / class: [Mock](https://github.com/moq/moq/blob/14615eefb49480c844a0ec1217cda6ff376cae62/spikes/v5/Moq/Mock.cs#L32)

Many of them uses representative name for namespace, and practical name for class.
I think it's best to follow the way.

If I select `Unibus` for class and select other word for namespace such as `UnibusFramework`, `UnibusSystem`, `UnibusLibrary`. It's seem to be not representative.
So I select the word `Event` for class.

``` cs
// It's representative!!
using Unibus;

// It's short and practical!!
Event.Dispatch();
Event.Subscribe();
Event.Unsubscribe();

// Or you can apply the package prefix naturally.
Unibus.Event.Dispatch();
Unibus.Event.Subscribe();
Unibus.Event.Unsubscribe();
```

Don't you think it's a good idea? @kazuman519

**Comment by mattak** [comment]
Sorry, I change word `Event` to `UnibusEvent`, Because `Event` is always conflict `UnityEngine.Event` in Unity3D.

``` cs
using Unibus;

UnibusEvent.Dispatch();
UnibusEvent.Subscribe();
UnibusEvent.Unsubscribe();
```

**Comment by mattak** [comment]
merged! 🎉
